### ISSUE TITLE
group.delete is sending wrong object type in __board

### ISSUE THREAD

**Issue by jhu321** [trix-solutions/moncli#219]
it looks like the api is looking for the __board.id str instead of the board object.  I'm not sure which is the intent, but i got it to work but making it send __board.id in my local version.

**Comment by Ashatz** [comment]
Hello @jhu321,

Thank you for bringing this issue to my attention.

The reason why the board object is passed into the group is due to the many functions in the board group that require the board_id for use.  Unfortunately, the API does not support querying the board containing the group, so moncli passes the containing board as you see.  

And as you say, the Board object is used as opposed to the required Board.id. 

This issue has been resolved with #223 and can be downloaded in v 2.0.14. Please let me know if you continue running into problems with this issue.

Thanks again!
