### ISSUE TITLE
Error while retrieving item with a special character

### ISSUE THREAD

**Issue by Omersh1** [trix-solutions/moncli#90]
Error while retrieving item with a special character

When searching for an item with apostrophe ('), I get this error:

('{"query": "query { items_by_column_values (board_id:499892072, column_id:\\"name\\", column_value:\\"BJ\\"s 
Wholesale Club\\") { id, name, created_at, creator_id, state } }", "variables": null}', 200, '', [{'message': 'Parse error on "Wholesale" (IDENTIFIER) at [1, 88]', 'locations': [{'line': 1, 'column': 88}]}])_

This is how I'm searching the item:
```
column_value = board.get_column_value(search_column_id)
column_value.name = value
item = board.get_items_by_column_values(column_value)
```

**Comment by booey811** [comment]
@Omersh1 I've has issues very similar to this while retrieving and writing objects to Monday. I believe it is an issue on their end as opposed to a problem with moncli. Their servers seem to have an issue dealing with scape characters

A solution is contained and explained (quite badly) here:

https://community.monday.com/t/error-on-parse-query-when-text-or-bad-request/2910

**Comment by Omersh1** [comment]
Hi @booey811, thank you!

It is not clear to me. Can you please share a code snippet/example of how did you do that?


Thanks!

**Comment by booey811** [comment]
Hi @Omersh1,

Super sorry for the massive delay, but this issue is almost certainly an error on the GraphQL server, please see the below article on the monday community:

https://community.monday.com/t/parse-error-on/12912/9

Read through that and try adjusting your query so that the "BJs Wholesale Club" has another set of single quote marks around it ('"BJs Wholesale Club"') and see what you come up with!

**Comment by Ashatz** [comment]
@booey811, thank you for taking the lead on this one!  I am closing this out now.  

Please expect faster turn-around time for bugs and issues moving forward.
